#!/usr/bin/env ruby
require 'optparse'
options = {
  :all => false,
  :location => File.expand_path(File.dirname(__FILE__) + '/../attractions'),
  :img_url => '/images/attractions/'
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: [-a] [-l FILE] [attraction_name]"
  
  opts.separator ""
  
  opts.on("-a", "--all", "Add all attractions in attractions folder.  Original post dates are preserverd, e.g. --all") do |a|
    options[:all] = a
  end
  
  opts.on("-l", "--location FILE", "Specify location for attractions, e.g. --location ~/attractions") do |l|
    options[:location] = File.expand_path(File.dirname(__FILE__) + '/../' + l)
  end
end
parser.parse! ARGV

class App
  attr_reader :args
  attr_reader :options
  def initialize(args,options)
    @args = args
    @options = options
  end
end

require File.expand_path(File.dirname(__FILE__)+"/../lib/add_attraction")
app = App.new ARGV, options
app.extend AddAttraction
app.run
#puts attributes
